const fs = require('fs');
const path = require('path');
const dotenv = require('dotenv');

dotenv.config({ path: path.join(__dirname, '..', '..', '.env') });

const { connectDB } = require('../config/db');
const User = require('../models/User');
const Content = require('../models/Content');
const Rating = require('../models/Rating');
const WatchHistory = require('../models/WatchHistory');
const SearchHistory = require('../models/SearchHistory');

const seedContent = [
  // ================= 32 MOVIES =================
  {
    title: "Interstellar",
    description: "When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot, Joseph Cooper, is tasked to pilot a spacecraft, along with a team of researchers, to find a new planet for humans.",
    type: "Movie",
    genres: ["Sci-Fi", "Drama", "Adventure"],
    language: "English",
    releaseYear: 2014,
    runtime: "169 min",
    rating: 8.7,
    ratingCount: 2150,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain", "Michael Caine"],
    director: "Christopher Nolan",
    popularity: 98,
    tags: ["space", "time dilation", "black hole", "emotional", "quantum"],
    moodTags: ["Curious", "Emotional", "Excited"]
  },
  {
    title: "Inception",
    description: "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
    type: "Movie",
    genres: ["Sci-Fi", "Action", "Thriller"],
    language: "English",
    releaseYear: 2010,
    runtime: "148 min",
    rating: 8.8,
    ratingCount: 3100,
    poster: "https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg",
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page", "Tom Hardy"],
    director: "Christopher Nolan",
    popularity: 96,
    tags: ["dreams", "heist", "mind-bending", "subconscious"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "The Dark Knight",
    description: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    type: "Movie",
    genres: ["Action", "Crime", "Drama"],
    language: "English",
    releaseYear: 2008,
    runtime: "152 min",
    rating: 9.0,
    ratingCount: 4200,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart", "Michael Caine"],
    director: "Christopher Nolan",
    popularity: 99,
    tags: ["batman", "joker", "gotham", "justice", "vigilante"],
    moodTags: ["Excited", "Scared"]
  },
  {
    title: "Oppenheimer",
    description: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    type: "Movie",
    genres: ["Drama", "History"],
    language: "English",
    releaseYear: 2023,
    runtime: "180 min",
    rating: 8.9,
    ratingCount: 1890,
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    trailer: "https://www.youtube.com/embed/uYPbbksJxIg",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon", "Robert Downey Jr."],
    director: "Christopher Nolan",
    popularity: 95,
    tags: ["physics", "atomic bomb", "manhattan project", "politics"],
    moodTags: ["Curious", "Emotional"]
  },
  {
    title: "Parasite",
    description: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.",
    type: "Movie",
    genres: ["Thriller", "Drama", "Comedy"],
    language: "Korean",
    releaseYear: 2019,
    runtime: "132 min",
    rating: 8.5,
    ratingCount: 1950,
    poster: "https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hiKmpnf79tMyvWhtxZjjwdqR4R1.jpg",
    trailer: "https://www.youtube.com/embed/5xH0RzeSojI",
    cast: ["Song Kang-ho", "Lee Sun-kyun", "Cho Yeo-jeong", "Choi Woo-shik"],
    director: "Bong Joon Ho",
    popularity: 94,
    tags: ["social class", "dark comedy", "oscar winner", "korea"],
    moodTags: ["Curious", "Scared"]
  },
  {
    title: "Vikram",
    description: "A high-octane action thriller where a special agent investigates a murder committed by a masked group of serial killers, unraveling a deep narcotics syndicate.",
    type: "Movie",
    genres: ["Action", "Thriller", "Crime"],
    language: "Tamil",
    releaseYear: 2022,
    runtime: "175 min",
    rating: 8.3,
    ratingCount: 2200,
    poster: "https://image.tmdb.org/t/p/w500/bLViU36lB7rQ48q8a1t8Yk73zF0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8s69V4vCqjH738u97Gf9y4Vp9v6.jpg",
    trailer: "https://www.youtube.com/embed/OKBMCL-frPU",
    cast: ["Kamal Haasan", "Vijay Sethupathi", "Fahadh Faasil", "Suriya"],
    director: "Lokesh Kanagaraj",
    popularity: 96,
    tags: ["lcu", "kamal haasan", "anirudh music", "action thriller"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Leo",
    description: "A calm cafe owner becomes a local hero through an act of violence, which triggers dark connections to a violent drug cartel that claims he is their lost son.",
    type: "Movie",
    genres: ["Action", "Thriller", "Drama"],
    language: "Tamil",
    releaseYear: 2023,
    runtime: "164 min",
    rating: 7.8,
    ratingCount: 2400,
    poster: "https://image.tmdb.org/t/p/w500/pD6sL4vntUOXHmuvJPPZAgvyfd9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ehmGk4zY59s3A0P11vPsmHspD1y.jpg",
    trailer: "https://www.youtube.com/embed/Po3jStA673E",
    cast: ["Thalapathy Vijay", "Trisha Krishnan", "Sanjay Dutt", "Arjun Sarja"],
    director: "Lokesh Kanagaraj",
    popularity: 97,
    tags: ["thalapathy vijay", "lcu", "kashmir", "action"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Ponniyin Selvan: Part 1",
    description: "Vandiyathevan sets out to cross the Chola land to deliver a message from Crown Prince Aditha Karikalan, sparking a grand political chess match for the Chola throne.",
    type: "Movie",
    genres: ["Drama", "Action", "Adventure"],
    language: "Tamil",
    releaseYear: 2022,
    runtime: "167 min",
    rating: 8.0,
    ratingCount: 1600,
    poster: "https://image.tmdb.org/t/p/w500/neAcr4X9f8D4l6x0e3j0A4Z8y4u.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/v28355j83a27fJ5551o96z27d7z.jpg",
    trailer: "https://www.youtube.com/embed/D4qAQYLGZVM",
    cast: ["Vikram", "Aishwarya Rai Bachchan", "Jayam Ravi", "Karthi", "Trisha"],
    director: "Mani Ratnam",
    popularity: 91,
    tags: ["chola empire", "mani ratnam", "ar rahman", "epic historical"],
    moodTags: ["Curious", "Emotional"]
  },
  {
    title: "Super Deluxe",
    description: "An unfaithful newlywed, an alienated son, a transgender woman, and a determined father face their demons on a fateful day in Chennai.",
    type: "Movie",
    genres: ["Drama", "Comedy", "Thriller"],
    language: "Tamil",
    releaseYear: 2019,
    runtime: "176 min",
    rating: 8.3,
    ratingCount: 980,
    poster: "https://image.tmdb.org/t/p/w500/3FfA3M2L7O51oH0TjD4l0o9J8J5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/x4A7T7U7eB1761qO4q0p3v8p5Q8.jpg",
    trailer: "https://www.youtube.com/embed/3-Xq_Zz3nPA",
    cast: ["Vijay Sethupathi", "Fahadh Faasil", "Samantha Ruth Prabhu", "Ramya Krishnan"],
    director: "Thiagarajan Kumararaja",
    popularity: 88,
    tags: ["anthology", "existential", "dark comedy", "chennai"],
    moodTags: ["Curious", "Funny"]
  },
  {
    title: "RRR",
    description: "A fearless revolutionary and an officer in the British force, who once were fierce friends, unite in an explosive rebellion against British rule in 1920s India.",
    type: "Movie",
    genres: ["Action", "Drama", "Adventure"],
    language: "Telugu",
    releaseYear: 2022,
    runtime: "187 min",
    rating: 8.8,
    ratingCount: 3800,
    poster: "https://image.tmdb.org/t/p/w500/nEufeZEiSEAUjKqxdIsAhRfX4t.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7kHkP1r6oPz1c0W1x9tP2jX8Y4z.jpg",
    trailer: "https://www.youtube.com/embed/NgBoMJy386M",
    cast: ["N.T. Rama Rao Jr.", "Ram Charan", "Alia Bhatt", "Ajay Devgn"],
    director: "S.S. Rajamouli",
    popularity: 99,
    tags: ["naatu naatu", "oscar winner", "epic action", "freedom fighters"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Baahubali 2: The Conclusion",
    description: "When Shiva, the son of Bahubali, learns about his heritage, he begins to look for answers while taking revenge against the tyrant Bhallaladeva.",
    type: "Movie",
    genres: ["Action", "Fantasy", "Drama"],
    language: "Telugu",
    releaseYear: 2017,
    runtime: "167 min",
    rating: 8.2,
    ratingCount: 2600,
    poster: "https://image.tmdb.org/t/p/w500/21sC2assImQIYCvv84nlRPv6xDO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/sS5oF9A5pXpX9gY6gT5gq7yF9o9.jpg",
    trailer: "https://www.youtube.com/embed/qD-6d8Wo3do",
    cast: ["Prabhas", "Rana Daggubati", "Anushka Shetty", "Tamannaah Bhatia"],
    director: "S.S. Rajamouli",
    popularity: 93,
    tags: ["mahismathi", "why kattappa killed baahubali", "mythology", "blockbuster"],
    moodTags: ["Excited", "Emotional"]
  },
  {
    title: "3 Idiots",
    description: "Two friends search for their long lost companion while revisiting their college days and memories of an unconventional friend who inspired them to think differently.",
    type: "Movie",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    releaseYear: 2009,
    runtime: "170 min",
    rating: 8.4,
    ratingCount: 3400,
    poster: "https://image.tmdb.org/t/p/w500/66A9MqXOyVFCssoloscw79z8Tew.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uDwG579cI6P11yA8pP111o274z0.jpg",
    trailer: "https://www.youtube.com/embed/K0eDlFX9GMc",
    cast: ["Aamir Khan", "Madhavan", "Sharman Joshi", "Kareena Kapoor"],
    director: "Rajkumar Hirani",
    popularity: 92,
    tags: ["engineering", "friendship", "inspirational", "all is well"],
    moodTags: ["Happy", "Funny"]
  },
  {
    title: "Dangal",
    description: "Former wrestler Mahavir Singh Phogat and his two wrestler daughters struggle towards glory at the Commonwealth Games in the face of societal oppression.",
    type: "Movie",
    genres: ["Drama", "Action"],
    language: "Hindi",
    releaseYear: 2016,
    runtime: "161 min",
    rating: 8.3,
    ratingCount: 2100,
    poster: "https://image.tmdb.org/t/p/w500/tA2kL0s8V4pG9X6bY7W1jL8Y4z5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wQG2gQx2p9J7gYQxX9gXy9x9X9g.jpg",
    trailer: "https://www.youtube.com/embed/x_7YlGv9u1g",
    cast: ["Aamir Khan", "Fatima Sana Shaikh", "Sanya Malhotra", "Sakshi Tanwar"],
    director: "Nitesh Tiwari",
    popularity: 91,
    tags: ["wrestling", "inspirational", "sports drama", "father daughter"],
    moodTags: ["Emotional", "Energetic"]
  },
  {
    title: "Manjummel Boys",
    description: "A group of friends from Kochi embark on a trip to Kodaikanal, where an unexpected mishap deep inside the Guna Caves tests their unbreakable bond of brotherhood.",
    type: "Movie",
    genres: ["Thriller", "Drama", "Adventure"],
    language: "Malayalam",
    releaseYear: 2024,
    runtime: "135 min",
    rating: 8.6,
    ratingCount: 1900,
    poster: "https://image.tmdb.org/t/p/w500/aH70U47U84Nq0f9LwZ8b8jX8Y4z.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bW1m2tO5X5y7Q0mP2Z4v8K1L9A7.jpg",
    trailer: "https://www.youtube.com/embed/id=dQw4w9WgXcQ",
    cast: ["Soubin Shahir", "Sreenath Bhasi", "Balu Varghese", "Ganapathi"],
    director: "Chidambaram",
    popularity: 95,
    tags: ["guna cave", "survival", "friendship", "kerala blockbuster"],
    moodTags: ["Excited", "Emotional"]
  },
  {
    title: "Premalu",
    description: "Sachin pursues romance in Hyderabad while getting caught up between different love interests and hilarious everyday situations.",
    type: "Movie",
    genres: ["Romance", "Comedy"],
    language: "Malayalam",
    releaseYear: 2024,
    runtime: "156 min",
    rating: 7.9,
    ratingCount: 1200,
    poster: "https://image.tmdb.org/t/p/w500/h5r8w7A0y9B8x9A0x6P9k9X8x9A.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/mQ8jWk7p9k8X8wY7p9qQ7yW8x8w.jpg",
    trailer: "https://www.youtube.com/embed/d96cjSVg85s",
    cast: ["Naslen K. Gafoor", "Mamitha Baiju", "Shyam Mohan", "Sangeeth Prathap"],
    director: "Girish A. D.",
    popularity: 90,
    tags: ["romcom", "feel-good", "hyderabad", "youth"],
    moodTags: ["Happy", "Romantic", "Funny"]
  },
  {
    title: "Kantara",
    description: "When greed paves the way for betrayal and murder, a young tribal man in coastal Karnataka channels his ancestors' spirit to defend his land and heritage.",
    type: "Movie",
    genres: ["Action", "Drama", "Mystery"],
    language: "Kannada",
    releaseYear: 2022,
    runtime: "148 min",
    rating: 8.2,
    ratingCount: 2800,
    poster: "https://image.tmdb.org/t/p/w500/xZ0oO2g0UfV2o5Y7W1jL8Y4z5A6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tX8x9A0y9B8x9A0x6P9k9X8x9A0.jpg",
    trailer: "https://www.youtube.com/embed/8mrVmf23aL4",
    cast: ["Rishab Shetty", "Sapthami Gowda", "Kishore", "Achyuth Kumar"],
    director: "Rishab Shetty",
    popularity: 93,
    tags: ["divine spirit", "boota kola", "folklore", "karnataka"],
    moodTags: ["Excited", "Curious"]
  },
  {
    title: "Dune: Part Two",
    description: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.",
    type: "Movie",
    genres: ["Sci-Fi", "Adventure", "Action"],
    language: "English",
    releaseYear: 2024,
    runtime: "166 min",
    rating: 8.6,
    ratingCount: 3500,
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0xO.jpg",
    trailer: "https://www.youtube.com/embed/Way9Dexny3w",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson", "Javier Bardem"],
    director: "Denis Villeneuve",
    popularity: 98,
    tags: ["arrakis", "sandworms", "spice", "prophecy"],
    moodTags: ["Excited", "Curious"]
  },
  {
    title: "Everything Everywhere All at Once",
    description: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.",
    type: "Movie",
    genres: ["Sci-Fi", "Action", "Comedy"],
    language: "English",
    releaseYear: 2022,
    runtime: "139 min",
    rating: 8.0,
    ratingCount: 2900,
    poster: "https://image.tmdb.org/t/p/w500/w3LxiVYPqrlexMmACbGl7YhuNcx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/9eAnVj9Jj23y225F05z95r03p60.jpg",
    trailer: "https://www.youtube.com/embed/wxN1T1uxQ2g",
    cast: ["Michelle Yeoh", "Stephanie Hsu", "Ke Huy Quan", "Jamie Lee Curtis"],
    director: "Daniels",
    popularity: 92,
    tags: ["multiverse", "absurdism", "oscar best picture", "family"],
    moodTags: ["Funny", "Emotional", "Curious"]
  },
  {
    title: "Spider-Man: Across the Spider-Verse",
    description: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    type: "Movie",
    genres: ["Animation", "Action", "Adventure"],
    language: "English",
    releaseYear: 2023,
    runtime: "140 min",
    rating: 8.7,
    ratingCount: 3900,
    poster: "https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    trailer: "https://www.youtube.com/embed/cqGjhVJWtEg",
    cast: ["Shameik Moore", "Hailee Steinfeld", "Oscar Isaac", "Daniel Kaluuya"],
    director: "Joaquim Dos Santos",
    popularity: 97,
    tags: ["spider-man", "multiverse", "gwen stacy", "groundbreaking animation"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Spirited Away",
    description: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches, and spirits, where humans are changed into beasts.",
    type: "Movie",
    genres: ["Animation", "Fantasy", "Adventure"],
    language: "Japanese",
    releaseYear: 2001,
    runtime: "125 min",
    rating: 8.6,
    ratingCount: 3300,
    poster: "https://image.tmdb.org/t/p/w500/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/Ab8mkHmkYADjU7wQiOkia99GQI.jpg",
    trailer: "https://www.youtube.com/embed/ByXuk9QqQkk",
    cast: ["Rumi Hiiragi", "Miyu Irino", "Mari Natsuki"],
    director: "Hayao Miyazaki",
    popularity: 95,
    tags: ["studio ghibli", "masterpiece", "miyazaki", "spirits"],
    moodTags: ["Relaxed", "Curious", "Happy"]
  },
  {
    title: "Your Name",
    description: "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?",
    type: "Movie",
    genres: ["Animation", "Romance", "Fantasy"],
    language: "Japanese",
    releaseYear: 2016,
    runtime: "106 min",
    rating: 8.4,
    ratingCount: 2700,
    poster: "https://image.tmdb.org/t/p/w500/vfJFJP9pqyaZu6j0umO0VsuULzq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dIWwZW7dJJ1q48oQWvXGgh0941.jpg",
    trailer: "https://www.youtube.com/embed/xU47nhruN-Q",
    cast: ["Ryunosuke Kamiki", "Mone Kamishiraishi", "Ryo Narita"],
    director: "Makoto Shinkai",
    popularity: 94,
    tags: ["body swap", "tokyo", "comet", "radwimps"],
    moodTags: ["Romantic", "Emotional"]
  },
  {
    title: "Past Lives",
    description: "Nora and Hae Sung, two deeply connected childhood friends, are wrest apart after Nora's family emigrates from South Korea. Decades later, they reunite for one fateful week.",
    type: "Movie",
    genres: ["Drama", "Romance"],
    language: "Korean",
    releaseYear: 2023,
    runtime: "105 min",
    rating: 7.9,
    ratingCount: 1400,
    poster: "https://image.tmdb.org/t/p/w500/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/w2nFc2Rsm93YjKVjY4DTTTqL9v.jpg",
    trailer: "https://www.youtube.com/embed/kA244xewjcI",
    cast: ["Greta Lee", "Teo Yoo", "John Magaro"],
    director: "Celine Song",
    popularity: 89,
    tags: ["inyeon", "destiny", "subtle", "a24"],
    moodTags: ["Emotional", "Romantic", "Lonely"]
  },
  {
    title: "Whiplash",
    description: "A promising young drummer enrolls at a cut-throat music conservatory where his dreams of greatness are mentored by an instructor who will stop at nothing to realize a student's potential.",
    type: "Movie",
    genres: ["Drama", "Music"],
    language: "English",
    releaseYear: 2014,
    runtime: "106 min",
    rating: 8.5,
    ratingCount: 2800,
    poster: "https://image.tmdb.org/t/p/w500/7fn624j5lj3xTme2SgiLCeuedmO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/f20Tq2A8wR4mH2w0k8L9k2B1x0.jpg",
    trailer: "https://www.youtube.com/embed/7d_jQycdQGo",
    cast: ["Miles Teller", "J.K. Simmons", "Paul Reiser"],
    director: "Damien Chazelle",
    popularity: 93,
    tags: ["jazz", "drums", "intensity", "perfection"],
    moodTags: ["Energetic", "Excited"]
  },
  {
    title: "Blade Runner 2049",
    description: "Young Blade Runner K's discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who's been missing for thirty years.",
    type: "Movie",
    genres: ["Sci-Fi", "Mystery", "Drama"],
    language: "English",
    releaseYear: 2017,
    runtime: "164 min",
    rating: 8.0,
    ratingCount: 2600,
    poster: "https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ilRyAZwNStG2Kei59x1K8w2xY7v.jpg",
    trailer: "https://www.youtube.com/embed/gCcx85zbxz4",
    cast: ["Ryan Gosling", "Harrison Ford", "Ana de Armas"],
    director: "Denis Villeneuve",
    popularity: 91,
    tags: ["cyberpunk", "replicants", "neon", "philosophical"],
    moodTags: ["Curious", "Lonely"]
  },
  {
    title: "The Shawshank Redemption",
    description: "Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.",
    type: "Movie",
    genres: ["Drama"],
    language: "English",
    releaseYear: 1994,
    runtime: "142 min",
    rating: 9.3,
    ratingCount: 5000,
    poster: "https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg",
    trailer: "https://www.youtube.com/embed/6hB3S9bIaco",
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    director: "Frank Darabont",
    popularity: 97,
    tags: ["prison", "hope", "friendship", "timeless"],
    moodTags: ["Emotional", "Relaxed"]
  },
  {
    title: "Pulp Fiction",
    description: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    type: "Movie",
    genres: ["Crime", "Drama"],
    language: "English",
    releaseYear: 1994,
    runtime: "154 min",
    rating: 8.9,
    ratingCount: 3800,
    poster: "https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg",
    trailer: "https://www.youtube.com/embed/s7EdQ4FqbhY",
    cast: ["John Travolta", "Uma Thurman", "Samuel L. Jackson", "Bruce Willis"],
    director: "Quentin Tarantino",
    popularity: 95,
    tags: ["nonlinear", "cult classic", "dialogue", "tarantino"],
    moodTags: ["Excited", "Funny"]
  },
  {
    title: "La La Land",
    description: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations for the future.",
    type: "Movie",
    genres: ["Comedy", "Drama", "Music", "Romance"],
    language: "English",
    releaseYear: 2016,
    runtime: "128 min",
    rating: 8.0,
    ratingCount: 2200,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkVJb0Rf0.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/qJeU7KM4nT7L4sNqGZ5L8z9V6V7.jpg",
    trailer: "https://www.youtube.com/embed/0pdqf4P9MB8",
    cast: ["Ryan Gosling", "Emma Stone", "John Legend"],
    director: "Damien Chazelle",
    popularity: 90,
    tags: ["jazz", "hollywood", "dreams", "musical"],
    moodTags: ["Romantic", "Emotional", "Happy"]
  },
  {
    title: "The Matrix",
    description: "When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.",
    type: "Movie",
    genres: ["Sci-Fi", "Action"],
    language: "English",
    releaseYear: 1999,
    runtime: "136 min",
    rating: 8.7,
    ratingCount: 4100,
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/l4QHerTSbMI7qgRPCzK3Kp1xOPa.jpg",
    trailer: "https://www.youtube.com/embed/vKQi3bBA1y8",
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    director: "Lana & Lilly Wachowski",
    popularity: 96,
    tags: ["cyberpunk", "simulation", "bullet time", "red pill"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "Oldboy",
    description: "After being kidnapped and imprisoned for fifteen years, Oh Dae-Su is released, only to find that he must find his captor in five days.",
    type: "Movie",
    genres: ["Action", "Drama", "Mystery", "Thriller"],
    language: "Korean",
    releaseYear: 2003,
    runtime: "120 min",
    rating: 8.4,
    ratingCount: 1700,
    poster: "https://image.tmdb.org/t/p/w500/pWDtjs568ZfOTMbURQBYuT4Qxka.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yB1bX6Yw5R1bX6Yw5R1bX6Yw5R.jpg",
    trailer: "https://www.youtube.com/embed/2HkjrJ6IK5E",
    cast: ["Choi Min-sik", "Yoo Ji-tae", "Kang Hye-jeong"],
    director: "Park Chan-wook",
    popularity: 89,
    tags: ["revenge", "hallway fight", "korean cinema", "twist"],
    moodTags: ["Scared", "Excited"]
  },
  {
    title: "Avengers: Endgame",
    description: "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
    type: "Movie",
    genres: ["Action", "Adventure", "Sci-Fi"],
    language: "English",
    releaseYear: 2019,
    runtime: "181 min",
    rating: 8.4,
    ratingCount: 4600,
    poster: "https://image.tmdb.org/t/p/w500/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1z9uJ4Z6K4m4M0.jpg",
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo", "Chris Hemsworth"],
    director: "Anthony & Joe Russo",
    popularity: 97,
    tags: ["marvel", "mcu", "thanos", "time heist"],
    moodTags: ["Excited", "Emotional", "Energetic"]
  },
  {
    title: "Jigarthanda DoubleX",
    description: "In 1975 Tamil Nadu, an unconventional filmmaker and an eccentric gangster team up to create a revolutionary western movie that transforms the community.",
    type: "Movie",
    genres: ["Action", "Comedy", "Drama"],
    language: "Tamil",
    releaseYear: 2023,
    runtime: "172 min",
    rating: 8.1,
    ratingCount: 1300,
    poster: "https://image.tmdb.org/t/p/w500/rM9A0y9B8x9A0x6P9k9X8x9A0y9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bW1m2tO5X5y7Q0mP2Z4v8K1L9A7.jpg",
    trailer: "https://www.youtube.com/embed/6iTqfM_pZ2c",
    cast: ["Raghava Lawrence", "S.J. Suryah", "Nimisha Sajayan"],
    director: "Karthik Subbaraj",
    popularity: 88,
    tags: ["western", "cinema", "elephant conservation", "karthik subbaraj"],
    moodTags: ["Excited", "Emotional", "Funny"]
  },
  {
    title: "Gangs of Wasseypur",
    description: "A clash between Sultan and Shahid Khan leads to the expulsion of Khan from Wasseypur, and ignites a deadly blood feud spanning three generations.",
    type: "Movie",
    genres: ["Action", "Crime", "Drama"],
    language: "Hindi",
    releaseYear: 2012,
    runtime: "321 min",
    rating: 8.2,
    ratingCount: 1900,
    poster: "https://image.tmdb.org/t/p/w500/qN7A0y9B8x9A0x6P9k9X8x9A0y9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dHjO0Oa1fV9p7qP2jX8Y4z5A6b.jpg",
    trailer: "https://www.youtube.com/embed/j-AkV3kS2yE",
    cast: ["Manoj Bajpayee", "Nawazuddin Siddiqui", "Tigmanshu Dhulia", "Richa Chadha"],
    director: "Anurag Kashyap",
    popularity: 90,
    tags: ["cult crime", "wasseypur", "revenge", "epic saga"],
    moodTags: ["Excited", "Scared"]
  },

  // ================= 21 TV & WEB SERIES =================
  {
    title: "Breaking Bad",
    description: "A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine with a former student to secure his family's financial future.",
    type: "TV Show",
    genres: ["Crime", "Drama", "Thriller"],
    language: "English",
    releaseYear: 2008,
    runtime: "47 min / ep",
    rating: 9.5,
    ratingCount: 4800,
    poster: "https://image.tmdb.org/t/p/w500/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    trailer: "https://www.youtube.com/embed/HhesaQXLuRY",
    cast: ["Bryan Cranston", "Aaron Paul", "Anna Gunn", "Giancarlo Esposito"],
    director: "Vince Gilligan",
    popularity: 99,
    tags: ["walter white", "heisenberg", "masterpiece", "albuquerque"],
    moodTags: ["Excited", "Curious"]
  },
  {
    title: "Stranger Things",
    description: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    type: "TV Show",
    genres: ["Sci-Fi", "Horror", "Drama"],
    language: "English",
    releaseYear: 2016,
    runtime: "51 min / ep",
    rating: 8.7,
    ratingCount: 3800,
    poster: "https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    trailer: "https://www.youtube.com/embed/b9EkMc79ZSU",
    cast: ["Millie Bobby Brown", "Finn Wolfhard", "Winona Ryder", "David Harbour"],
    director: "The Duffer Brothers",
    popularity: 98,
    tags: ["upside down", "eighties", "demogorgon", "nostalgia"],
    moodTags: ["Scared", "Excited", "Curious"]
  },
  {
    title: "Dark",
    description: "A family saga with a supernatural twist, set in a German town where the disappearance of two young children exposes the relationships among four families.",
    type: "TV Show",
    genres: ["Sci-Fi", "Mystery", "Thriller"],
    language: "German",
    releaseYear: 2017,
    runtime: "60 min / ep",
    rating: 8.7,
    ratingCount: 2900,
    poster: "https://image.tmdb.org/t/p/w500/apbrQrKcCy07vViiSkn6797059q.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/3lBDg3i6nn5R2NKICJ3q9C1p1P9.jpg",
    trailer: "https://www.youtube.com/embed/rrwycJ08PSA",
    cast: ["Louis Hofmann", "Karoline Eichhorn", "Lisa Vicari", "Maja Schöne"],
    director: "Baran bo Odar",
    popularity: 94,
    tags: ["time travel", "mind-bending", "winden", "apocalypse"],
    moodTags: ["Curious", "Lonely"]
  },
  {
    title: "Succession",
    description: "The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their aging father steps down from the company.",
    type: "TV Show",
    genres: ["Drama"],
    language: "English",
    releaseYear: 2018,
    runtime: "60 min / ep",
    rating: 8.9,
    ratingCount: 2600,
    poster: "https://image.tmdb.org/t/p/w500/7udW8aD50Qx7ePz768qE8v61p6K.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/e9n0U0Oa1fV9p7qP2jX8Y4z5A6b.jpg",
    trailer: "https://www.youtube.com/embed/OzYxJV_rmE8",
    cast: ["Brian Cox", "Jeremy Strong", "Sarah Snook", "Kieran Culkin"],
    director: "Jesse Armstrong",
    popularity: 96,
    tags: ["corporate", "billionaires", "satire", "power struggle"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "The Last of Us",
    description: "After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity's last hope.",
    type: "TV Show",
    genres: ["Drama", "Action", "Sci-Fi"],
    language: "English",
    releaseYear: 2023,
    runtime: "55 min / ep",
    rating: 8.8,
    ratingCount: 3100,
    poster: "https://image.tmdb.org/t/p/w500/uKvVjK1qsvx40k5fI2h5sM761p6.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    trailer: "https://www.youtube.com/embed/uLtkt8BonwM",
    cast: ["Pedro Pascal", "Bella Ramsey", "Gabriel Luna", "Anna Torv"],
    director: "Craig Mazin",
    popularity: 97,
    tags: ["post-apocalyptic", "cordyceps", "joel and ellie", "gaming adaptation"],
    moodTags: ["Emotional", "Excited"]
  },
  {
    title: "Squid Game",
    description: "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    type: "Web Series",
    genres: ["Thriller", "Mystery", "Drama"],
    language: "Korean",
    releaseYear: 2021,
    runtime: "55 min / ep",
    rating: 8.0,
    ratingCount: 4200,
    poster: "https://image.tmdb.org/t/p/w500/dDlG1Tz9V1Q1Tz9V1Q1Tz9V1Q1.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/oaGvjB0DvdNDbdPtHJUrGagRmgd.jpg",
    trailer: "https://www.youtube.com/embed/oqxAJKy0ii4",
    cast: ["Lee Jung-jae", "Park Hae-soo", "Wi Ha-joon", "Jung Ho-yeon"],
    director: "Hwang Dong-hyuk",
    popularity: 98,
    tags: ["red light green light", "survival game", "korean sensation"],
    moodTags: ["Scared", "Excited"]
  },
  {
    title: "Suzhal - The Vortex",
    description: "An investigation into a missing girl during a local micro-festival in a small industrial town in Tamil Nadu unearths secrets that tear the social fabric apart.",
    type: "Web Series",
    genres: ["Crime", "Mystery", "Thriller"],
    language: "Tamil",
    releaseYear: 2022,
    runtime: "45 min / ep",
    rating: 8.2,
    ratingCount: 1100,
    poster: "https://image.tmdb.org/t/p/w500/xY0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8s69V4vCqjH738u97Gf9y4Vp9v6.jpg",
    trailer: "https://www.youtube.com/embed/xJ84sK9KqGk",
    cast: ["Kathir", "Aishwarya Rajesh", "R. Parthiban", "Sriya Reddy"],
    director: "Pushkar & Gayatri",
    popularity: 87,
    tags: ["mayana kollai", "whodunit", "tamil series", "suspense"],
    moodTags: ["Curious", "Scared"]
  },
  {
    title: "The Family Man",
    description: "A working-class man from the National Investigation Agency struggles to balance his secretive, low-paying high-risk job with his demanding middle-class family duties.",
    type: "Web Series",
    genres: ["Action", "Comedy", "Drama"],
    language: "Hindi",
    releaseYear: 2019,
    runtime: "45 min / ep",
    rating: 8.7,
    ratingCount: 3200,
    poster: "https://image.tmdb.org/t/p/w500/nF0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uDwG579cI6P11yA8pP111o274z0.jpg",
    trailer: "https://www.youtube.com/embed/ng79lK05wWc",
    cast: ["Manoj Bajpayee", "Priyamani", "Sharib Hashmi", "Samantha Ruth Prabhu"],
    director: "Raj & DK",
    popularity: 94,
    tags: ["spy thriller", "tiwari", "middle class", "national security"],
    moodTags: ["Excited", "Funny"]
  },
  {
    title: "Mirzapur",
    description: "A shocking incident at a wedding procession ignites a series of events entangling two families in the lawless belt of Purvanchal.",
    type: "Web Series",
    genres: ["Crime", "Action", "Drama"],
    language: "Hindi",
    releaseYear: 2018,
    runtime: "50 min / ep",
    rating: 8.5,
    ratingCount: 3600,
    poster: "https://image.tmdb.org/t/p/w500/kY0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7kHkP1r6oPz1c0W1x9tP2jX8Y4z.jpg",
    trailer: "https://www.youtube.com/embed/ZNeGF-PvVHY",
    cast: ["Pankaj Tripathi", "Ali Fazal", "Divyenndu", "Shweta Tripathi"],
    director: "Karan Anshuman",
    popularity: 95,
    tags: ["kaleen bhaiya", "guddu", "guns", "revenge"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Sacred Games",
    description: "A link in their pasts leads an honest cop to a fugitive gang boss, whose cryptic warning spurs the officer on a quest to save Mumbai from cataclysm.",
    type: "Web Series",
    genres: ["Crime", "Mystery", "Drama"],
    language: "Hindi",
    releaseYear: 2018,
    runtime: "50 min / ep",
    rating: 8.5,
    ratingCount: 2900,
    poster: "https://image.tmdb.org/t/p/w500/mY0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    trailer: "https://www.youtube.com/embed/28j8h0RRsf4",
    cast: ["Saif Ali Khan", "Nawazuddin Siddiqui", "Radhika Apte", "Pankaj Tripathi"],
    director: "Anurag Kashyap & Vikramaditya Motwane",
    popularity: 92,
    tags: ["gaitonde", "sartaj", "mumbai underworld", "thriller"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "Chernobyl",
    description: "In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world's worst man-made catastrophes.",
    type: "TV Show",
    genres: ["Drama", "History", "Thriller"],
    language: "English",
    releaseYear: 2019,
    runtime: "65 min / ep",
    rating: 9.4,
    ratingCount: 3700,
    poster: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uL6Ad12Fe4iatxPknFWHgE4YTIU.jpg",
    trailer: "https://www.youtube.com/embed/s9APLXM9Ei8",
    cast: ["Jared Harris", "Stellan Skarsgård", "Emily Watson", "Paul Ritter"],
    director: "Craig Mazin",
    popularity: 95,
    tags: ["nuclear disaster", "historical truth", "hbo miniseries", "gripping"],
    moodTags: ["Curious", "Scared"]
  },
  {
    title: "Severance",
    description: "Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.",
    type: "TV Show",
    genres: ["Sci-Fi", "Thriller", "Mystery"],
    language: "English",
    releaseYear: 2022,
    runtime: "50 min / ep",
    rating: 8.7,
    ratingCount: 2200,
    poster: "https://image.tmdb.org/t/p/w500/pPHpehvTnLq94GBwWzpBpzIknJR.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8tT8Y1s7K8Y1s7K8Y1s7K8Y1s7.jpg",
    trailer: "https://www.youtube.com/embed/xEQP4VVuyrY",
    cast: ["Adam Scott", "Zach Cherry", "Britt Lower", "Patricia Arquette"],
    director: "Ben Stiller",
    popularity: 93,
    tags: ["lumon", "dystopian workplace", "psychological", "apple tv"],
    moodTags: ["Curious", "Lonely"]
  },
  {
    title: "Game of Thrones",
    description: "Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.",
    type: "TV Show",
    genres: ["Action", "Adventure", "Drama", "Fantasy"],
    language: "English",
    releaseYear: 2011,
    runtime: "57 min / ep",
    rating: 9.2,
    ratingCount: 5200,
    poster: "https://image.tmdb.org/t/p/w500/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    trailer: "https://www.youtube.com/embed/KPLWWIOCOOQ",
    cast: ["Emilia Clarke", "Peter Dinklage", "Kit Harington", "Lena Headey"],
    director: "David Benioff & D.B. Weiss",
    popularity: 98,
    tags: ["dragons", "iron throne", "westeros", "winter is coming"],
    moodTags: ["Excited", "Curious"]
  },
  {
    title: "The Bear",
    description: "A young fine-dining chef returns home to Chicago to run his family's Italian beef sandwich shop after a heartbreaking death in the family.",
    type: "TV Show",
    genres: ["Comedy", "Drama"],
    language: "English",
    releaseYear: 2022,
    runtime: "35 min / ep",
    rating: 8.6,
    ratingCount: 2300,
    poster: "https://image.tmdb.org/t/p/w500/n9A0y9B8x9A0x6P9k9X8x9A0y9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rX9A0y9B8x9A0x6P9k9X8x9A0y9.jpg",
    trailer: "https://www.youtube.com/embed/y-cHg_k_eFE",
    cast: ["Jeremy Allen White", "Ebon Moss-Bachrach", "Ayo Edebiri", "Liza Colón-Zayas"],
    director: "Christopher Storer",
    popularity: 94,
    tags: ["yes chef", "chicago", "kitchen intensity", "emmy winner"],
    moodTags: ["Energetic", "Emotional", "Funny"]
  },
  {
    title: "All of Us Are Dead",
    description: "A high school becomes ground zero for a zombie virus outbreak. Trapped students must fight their way out or turn into one of the rabid infected.",
    type: "Web Series",
    genres: ["Action", "Horror", "Sci-Fi"],
    language: "Korean",
    releaseYear: 2022,
    runtime: "60 min / ep",
    rating: 7.5,
    ratingCount: 1900,
    poster: "https://image.tmdb.org/t/p/w500/8jA0y9B8x9A0x6P9k9X8x9A0y9.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/oaGvjB0DvdNDbdPtHJUrGagRmgd.jpg",
    trailer: "https://www.youtube.com/embed/IN5TD4VRcMo",
    cast: ["Park Ji-hu", "Yoon Chan-young", "Cho Yi-hyun", "Lomon"],
    director: "Lee Jae-kyoo",
    popularity: 91,
    tags: ["zombies", "high school", "korean survival", "action-packed"],
    moodTags: ["Scared", "Excited"]
  },
  {
    title: "Money Heist",
    description: "An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.",
    type: "TV Show",
    genres: ["Action", "Crime", "Mystery"],
    language: "Spanish",
    releaseYear: 2017,
    runtime: "50 min / ep",
    rating: 8.2,
    ratingCount: 3700,
    poster: "https://image.tmdb.org/t/p/w500/reEMJA1uzscCbk5r6lgEjXujn38.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gFZri2YbFUEtSQSflftRiIGjKuE.jpg",
    trailer: "https://www.youtube.com/embed/_InqQJRqGW4",
    cast: ["Úrsula Corberó", "Álvaro Morte", "Itziar Ituño", "Pedro Alonso"],
    director: "Álex Pina",
    popularity: 95,
    tags: ["professor", "bella ciao", "dali mask", "heist"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Panchayat",
    description: "An engineering graduate takes up a job as a secretary of a Gram Panchayat in a remote village of Uttar Pradesh due to lack of better job options.",
    type: "Web Series",
    genres: ["Comedy", "Drama"],
    language: "Hindi",
    releaseYear: 2020,
    runtime: "35 min / ep",
    rating: 8.9,
    ratingCount: 3100,
    poster: "https://image.tmdb.org/t/p/w500/pY0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uDwG579cI6P11yA8pP111o274z0.jpg",
    trailer: "https://www.youtube.com/embed/mojZJ7oeD_g",
    cast: ["Jitendra Kumar", "Raghubir Yadav", "Neena Gupta", "Chandan Roy"],
    director: "Deepak Kumar Mishra",
    popularity: 94,
    tags: ["phulera", "rural life", "warm comedy", "tvf"],
    moodTags: ["Happy", "Relaxed", "Funny"]
  },
  {
    title: "Scam 1992: The Harshad Mehta Story",
    description: "Set in 1980s and 90s Bombay, the series follows the life of Harshad Mehta, a stockbroker who took the stock market to dizzying heights and his catastrophic downfall.",
    type: "Web Series",
    genres: ["Drama", "Crime"],
    language: "Hindi",
    releaseYear: 2020,
    runtime: "50 min / ep",
    rating: 9.3,
    ratingCount: 2900,
    poster: "https://image.tmdb.org/t/p/w500/sY0u84Nq0f9LwZ8b8jX8Y4z5A6b.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/wQG2gQx2p9J7gYQxX9gXy9x9X9g.jpg",
    trailer: "https://www.youtube.com/embed/ISORfez27og",
    cast: ["Pratik Gandhi", "Shreya Dhanwanthary", "Hemant Kher"],
    director: "Hansal Mehta",
    popularity: 93,
    tags: ["bombay stock exchange", "risk hai toh ishq hai", "financial thriller"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "Better Call Saul",
    description: "The trials and tribulations of criminal lawyer Jimmy McGill in the years leading up to his fateful run-in with Walter White and Jesse Pinkman.",
    type: "TV Show",
    genres: ["Crime", "Drama"],
    language: "English",
    releaseYear: 2015,
    runtime: "50 min / ep",
    rating: 9.0,
    ratingCount: 3200,
    poster: "https://image.tmdb.org/t/p/w500/fC2HDm5t0kHVR79visHQBYHpX92.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/hPea3Qy5Gd6z4GNumRvgKp92ftv.jpg",
    trailer: "https://www.youtube.com/embed/HN4oyhmgoP4",
    cast: ["Bob Odenkirk", "Rhea Seehorn", "Jonathan Banks", "Giancarlo Esposito"],
    director: "Vince Gilligan & Peter Gould",
    popularity: 95,
    tags: ["saul goodman", "lawyer", "breaking bad prequel", "kim wexler"],
    moodTags: ["Curious", "Emotional"]
  },
  {
    title: "Sherlock",
    description: "A modern update finds the famous sleuth and his doctor partner solving crime in 21st-century London.",
    type: "TV Show",
    genres: ["Crime", "Drama", "Mystery"],
    language: "English",
    releaseYear: 2010,
    runtime: "88 min / ep",
    rating: 9.1,
    ratingCount: 3900,
    poster: "https://image.tmdb.org/t/p/w500/7WTsnM45AAYhoI13k9172fQ1v4L.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/bvB4eA66a5V8uO8rM9O7iZ8j5qA.jpg",
    trailer: "https://www.youtube.com/embed/xK7S9mrFWL4",
    cast: ["Benedict Cumberbatch", "Martin Freeman", "Una Stubbs", "Andrew Scott"],
    director: "Steven Moffat & Mark Gatiss",
    popularity: 96,
    tags: ["deduction", "baker street", "moriarty", "genius"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "Narcos",
    description: "A chronicled look at the criminal exploits of Colombian drug lord Pablo Escobar, as well as the many other drug kingpins who plagued the country through the years.",
    type: "TV Show",
    genres: ["Biography", "Crime", "Drama"],
    language: "English",
    releaseYear: 2015,
    runtime: "49 min / ep",
    rating: 8.8,
    ratingCount: 3400,
    poster: "https://image.tmdb.org/t/p/w500/rTmal9fVCwhv9nR9OIaqLW2Kpcu.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fIK18uT3C4u8F9uP8w1V4v5o6w8.jpg",
    trailer: "https://www.youtube.com/embed/xl8hmgM34yo",
    cast: ["Wagner Moura", "Pedro Pascal", "Boyd Holbrook"],
    director: "Chris Brancato",
    popularity: 93,
    tags: ["medellin cartel", "dea", "plata o plomo", "colombia"],
    moodTags: ["Excited", "Scared"]
  },

  // ================= 15 ANIME =================
  {
    title: "Attack on Titan",
    description: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    type: "Anime",
    genres: ["Animation", "Action", "Fantasy"],
    language: "Japanese",
    releaseYear: 2013,
    runtime: "24 min / ep",
    rating: 9.1,
    ratingCount: 4700,
    poster: "https://cdn.myanimelist.net/images/anime/10/47347l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/i7UeGz8P3y45Gj0X7O9u5g3s5.jpg",
    trailer: "https://www.youtube.com/embed/MGRm4IzK1SQ",
    cast: ["Yuki Kaji", "Yui Ishikawa", "Marina Inoue", "Hiroshi Kamiya"],
    director: "Tetsuro Araki",
    popularity: 99,
    tags: ["eren yeager", "shingeki no kyojin", "scout regiment", "titans"],
    moodTags: ["Excited", "Energetic", "Emotional"]
  },
  {
    title: "Death Note",
    description: "An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.",
    type: "Anime",
    genres: ["Animation", "Mystery", "Thriller"],
    language: "Japanese",
    releaseYear: 2006,
    runtime: "23 min / ep",
    rating: 9.0,
    ratingCount: 4200,
    poster: "https://cdn.myanimelist.net/images/anime/9/9453l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tGOC9A174oO1o4p6V8k9w0z8y.jpg",
    trailer: "https://www.youtube.com/embed/NlJZ-YgAt-c",
    cast: ["Mamoru Miyano", "Kappei Yamaguchi", "Shidou Nakamura"],
    director: "Tetsuro Araki",
    popularity: 97,
    tags: ["light yagami", "l", "shinigami ryuk", "cat and mouse"],
    moodTags: ["Curious", "Scared"]
  },
  {
    title: "Demon Slayer: Kimetsu no Yaiba",
    description: "A youth begins a quest to fight demons and turn his sister human again after his family is slaughtered and she is turned into a demon.",
    type: "Anime",
    genres: ["Animation", "Action", "Fantasy"],
    language: "Japanese",
    releaseYear: 2019,
    runtime: "24 min / ep",
    rating: 8.7,
    ratingCount: 3900,
    poster: "https://cdn.myanimelist.net/images/anime/1286/99889l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/nTvM4mhqZlHIvPtPRum9WXvdmr9.jpg",
    trailer: "https://www.youtube.com/embed/VQGCKyvzIM4",
    cast: ["Natsuki Hanae", "Akari Kito", "Hiro Shimono"],
    director: "Haruo Sotozaki",
    popularity: 98,
    tags: ["tanjiro", "nezuko", "ufotable", "swordsmith"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Jujutsu Kaisen",
    description: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself. He enters a shaman's school to be able to locate the demon's other body parts and thus exorcise himself.",
    type: "Anime",
    genres: ["Animation", "Action", "Fantasy"],
    language: "Japanese",
    releaseYear: 2020,
    runtime: "24 min / ep",
    rating: 8.6,
    ratingCount: 3600,
    poster: "https://cdn.myanimelist.net/images/anime/1171/109222l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/gmECX1DvY4hiBDx97zzyqkmTzEX.jpg",
    trailer: "https://www.youtube.com/embed/pkZXflp_e_Y",
    cast: ["Junya Enoki", "Yuma Uchida", "Asami Seto", "Yuichi Nakamura"],
    director: "Sunghoo Park",
    popularity: 98,
    tags: ["satoru gojo", "sukuna", "domain expansion", "mappa"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Fullmetal Alchemist: Brotherhood",
    description: "Two brothers search for a Philosopher's Stone after an attempt to revive their deceased mother goes awry and leaves them in damaged physical forms.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure", "Fantasy"],
    language: "Japanese",
    releaseYear: 2009,
    runtime: "24 min / ep",
    rating: 9.1,
    ratingCount: 4100,
    poster: "https://cdn.myanimelist.net/images/anime/1223/96541l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/7kHkP1r6oPz1c0W1x9tP2jX8Y4z.jpg",
    trailer: "https://www.youtube.com/embed/cp6vBq_8qX8",
    cast: ["Romi Park", "Rie Kugimiya", "Megumi Toyoguchi"],
    director: "Yasuhiro Irie",
    popularity: 96,
    tags: ["alchemy", "edward elric", "equivalent exchange", "homunculus"],
    moodTags: ["Emotional", "Excited"]
  },
  {
    title: "Naruto Shippuden",
    description: "Naruto Uzumaki, is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninja in the village.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure"],
    language: "Japanese",
    releaseYear: 2007,
    runtime: "24 min / ep",
    rating: 8.7,
    ratingCount: 4500,
    poster: "https://cdn.myanimelist.net/images/anime/1565/111305l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    trailer: "https://www.youtube.com/embed/1dyn28mHnVE",
    cast: ["Junko Takeuchi", "Noriaki Sugiyama", "Chie Nakamura"],
    director: "Hayato Date",
    popularity: 97,
    tags: ["ninja", "rasengan", "sasuke", "konoha", "akatsuki"],
    moodTags: ["Energetic", "Excited"]
  },
  {
    title: "One Piece",
    description: "Follows the adventures of Monkey D. Luffy and his pirate crew in order to find the greatest treasure ever left by the legendary Pirate, Gold Roger, the famous mystery treasure named 'One Piece'.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure", "Comedy"],
    language: "Japanese",
    releaseYear: 1999,
    runtime: "24 min / ep",
    rating: 9.0,
    ratingCount: 4900,
    poster: "https://cdn.myanimelist.net/images/anime/6/73245l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    trailer: "https://www.youtube.com/embed/l_98K4_6UQ0",
    cast: ["Mayumi Tanaka", "Akemi Okamura", "Kazuya Nakai"],
    director: "Eiichiro Oda (Creator)",
    popularity: 99,
    tags: ["luffy", "straw hats", "grand line", "devil fruit"],
    moodTags: ["Happy", "Excited", "Energetic"]
  },
  {
    title: "Chainsaw Man",
    description: "Following a betrayal, a young man left for the dead is reborn as a powerful chainsaw devil and joins a governmental agency hunting devils.",
    type: "Anime",
    genres: ["Animation", "Action", "Horror"],
    language: "Japanese",
    releaseYear: 2022,
    runtime: "24 min / ep",
    rating: 8.5,
    ratingCount: 2800,
    poster: "https://cdn.myanimelist.net/images/anime/1806/126216l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/8tT8Y1s7K8Y1s7K8Y1s7K8Y1s7.jpg",
    trailer: "https://www.youtube.com/embed/v4yLeNt-kCU",
    cast: ["Kikunosuke Toya", "Tomori Kusunoki", "Shogo Sakata"],
    director: "Ryu Nakayama",
    popularity: 94,
    tags: ["denji", "makima", "pochita", "mappa"],
    moodTags: ["Excited", "Scared"]
  },
  {
    title: "Vinland Saga",
    description: "Thorfinn pursues a journey with his father's killer in order to take revenge and end his life in a duel, paying tribute to his Viking ancestors.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure"],
    language: "Japanese",
    releaseYear: 2019,
    runtime: "24 min / ep",
    rating: 8.8,
    ratingCount: 2600,
    poster: "https://cdn.myanimelist.net/images/anime/1500/103005l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    trailer: "https://www.youtube.com/embed/f8JrZ7Q_tcg",
    cast: ["Yuto Uemura", "Naoya Uchida", "Kensho Ono"],
    director: "Shuhei Yabuta",
    popularity: 93,
    tags: ["vikings", "askeladd", "thorfinn", "historical"],
    moodTags: ["Emotional", "Excited"]
  },
  {
    title: "Hunter x Hunter",
    description: "Gon Freecss aspires to become a Hunter, an exceptional being capable of greatness. With his friends, he embarks on an odyssey that far outstrips the limits of common imagination.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure"],
    language: "Japanese",
    releaseYear: 2011,
    runtime: "24 min / ep",
    rating: 9.0,
    ratingCount: 3900,
    poster: "https://cdn.myanimelist.net/images/anime/1337/99726l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    trailer: "https://www.youtube.com/embed/d6kBeJjTGnY",
    cast: ["Megumi Han", "Mariya Ise", "Keiji Fujiwara"],
    director: "Hiroshi Koujina",
    popularity: 96,
    tags: ["gon", "killua", "nen", "chimera ant arc"],
    moodTags: ["Excited", "Emotional"]
  },
  {
    title: "Solo Leveling",
    description: "In a world where hunters must battle deadly monsters to protect the human race, the notoriously weak hunter Sung Jinwoo finds himself in a seemingly endless struggle for survival.",
    type: "Anime",
    genres: ["Animation", "Action", "Fantasy"],
    language: "Japanese",
    releaseYear: 2024,
    runtime: "24 min / ep",
    rating: 8.5,
    ratingCount: 2900,
    poster: "https://cdn.myanimelist.net/images/anime/1598/141011l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    trailer: "https://www.youtube.com/embed/4p15k8lq5o4",
    cast: ["Taito Ban", "Genta Nakamura", "Reina Ueda"],
    director: "Shunsuke Nakashige",
    popularity: 97,
    tags: ["shadow monarch", "dungeon", "manhwa adaptation", "overpowered"],
    moodTags: ["Excited", "Energetic"]
  },
  {
    title: "Steins;Gate",
    description: "After discovering time travel, a university student and his eccentric colleagues must find a way to stop an evil organization and their malicious plots.",
    type: "Anime",
    genres: ["Animation", "Sci-Fi", "Thriller"],
    language: "Japanese",
    releaseYear: 2011,
    runtime: "24 min / ep",
    rating: 9.1,
    ratingCount: 3100,
    poster: "https://cdn.myanimelist.net/images/anime/1935/127974l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/3lBDg3i6nn5R2NKICJ3q9C1p1P9.jpg",
    trailer: "https://www.youtube.com/embed/uMYhjVwp0Fk",
    cast: ["Mamoru Miyano", "Asami Imai", "Kana Hanazawa"],
    director: "Hiroshi Hamasaki & Takuya Sato",
    popularity: 94,
    tags: ["time travel", "microwave", "okabe rintaro", "kurisu makise"],
    moodTags: ["Curious", "Emotional"]
  },
  {
    title: "Cyberpunk: Edgerunners",
    description: "A street kid trying to survive in a technology and body modification-obsessed city of the future decides to stay alive by becoming an edgerunner: a mercenary outlaw.",
    type: "Anime",
    genres: ["Animation", "Action", "Sci-Fi"],
    language: "Japanese",
    releaseYear: 2022,
    runtime: "24 min / ep",
    rating: 8.3,
    ratingCount: 2700,
    poster: "https://cdn.myanimelist.net/images/anime/1861/126442l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/ilRyAZwNStG2Kei59x1K8w2xY7v.jpg",
    trailer: "https://www.youtube.com/embed/JtqIas3bYhg",
    cast: ["KENN", "Aoi Yuuki", "Hiroki Touchi"],
    director: "Hiroyuki Imaishi",
    popularity: 93,
    tags: ["night city", "david martinez", "lucy", "trigger"],
    moodTags: ["Energetic", "Excited", "Emotional"]
  },
  {
    title: "Cowboy Bebop",
    description: "The futuristic misadventures and tragedies of an easygoing bounty hunter and his eccentric partners in 2071 space.",
    type: "Anime",
    genres: ["Animation", "Action", "Adventure", "Sci-Fi"],
    language: "Japanese",
    releaseYear: 1998,
    runtime: "24 min / ep",
    rating: 8.9,
    ratingCount: 3300,
    poster: "https://cdn.myanimelist.net/images/anime/4/19644l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fIK18uT3C4u8F9uP8w1V4v5o6w8.jpg",
    trailer: "https://www.youtube.com/embed/EL-D9LrFJd4",
    cast: ["Koichi Yamadera", "Unsho Ishizuka", "Megumi Hayashibara"],
    director: "Shinichiro Watanabe",
    popularity: 92,
    tags: ["jazz", "space bounty hunter", "spike spiegel", "see you space cowboy"],
    moodTags: ["Relaxed", "Lonely", "Curious"]
  },
  {
    title: "Bleach: Thousand-Year Blood War",
    description: "The peace is suddenly broken when warning sirens blare through the Soul Society. Residents are disappearing without a trace and nobody knows who is behind it.",
    type: "Anime",
    genres: ["Animation", "Action", "Fantasy"],
    language: "Japanese",
    releaseYear: 2022,
    runtime: "24 min / ep",
    rating: 9.0,
    ratingCount: 2500,
    poster: "https://cdn.myanimelist.net/images/anime/1764/126627l.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    trailer: "https://www.youtube.com/embed/e8YBesRKq_U",
    cast: ["Masakazu Morita", "Fumiko Orikasa", "Noriaki Sugiyama"],
    director: "Tomohisa Taguchi",
    popularity: 94,
    tags: ["ichigo kurosaki", "bankai", "quincy", "soul society"],
    moodTags: ["Excited", "Energetic"]
  },

  // ================= 15 MUSIC ENTRIES =================
  {
    title: "Discovery",
    description: "The groundbreaking second electronic studio album by French electronic music duo Daft Punk, featuring timeless synthesizers and futuristic club anthems.",
    type: "Music",
    genres: ["Musical", "Adventure"],
    language: "English",
    releaseYear: 2001,
    runtime: "61 min",
    rating: 9.1,
    ratingCount: 1800,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music221/v4/fd/4a/77/fd4a77db-0ebc-d043-41a2-f32fa1bb0fb4/dj.qrikkdwj.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/FGBhQbmPwH8",
    cast: ["Thomas Bangalter", "Guy-Manuel de Homem-Christo"],
    director: "Daft Punk",
    popularity: 94,
    tags: ["one more time", "harder better faster stronger", "electronic", "french touch"],
    moodTags: ["Energetic", "Happy"]
  },
  {
    title: "Hans Zimmer - Live in Prague",
    description: "A breathtaking live concert performance capturing the legendary composer performing his most iconic scores including Inception, Gladiator, Interstellar, and The Dark Knight.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2017,
    runtime: "138 min",
    rating: 9.3,
    ratingCount: 2200,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/21/df/b6/21dfb689-0ea7-0487-d4fa-ae0923be2a9b/886446736208.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/1kQZ2uLp4r0",
    cast: ["Hans Zimmer", "Guthrie Govan", "Johnny Marr"],
    director: "Tim Van Someren",
    popularity: 95,
    tags: ["orchestra", "film score", "epic music", "time"],
    moodTags: ["Emotional", "Curious", "Relaxed"]
  },
  {
    title: "A.R. Rahman: Best of Pure Soundtracks",
    description: "An evocative master collection of the Academy Award-winning composer's finest cinematic creations across Roja, Bombay, Dil Se, and Ponniyin Selvan.",
    type: "Music",
    genres: ["Musical", "Romance"],
    language: "Tamil",
    releaseYear: 2023,
    runtime: "95 min",
    rating: 9.4,
    ratingCount: 3100,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/d9/95/92/d99592f6-b18c-3be0-a359-dc71a2a46cbf/8902894353848_cover.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/9g_hKov_p1Q",
    cast: ["A.R. Rahman", "Hariharan", "K.S. Chithra", "Shreya Ghoshal"],
    director: "A.R. Rahman",
    popularity: 97,
    tags: ["mozart of madras", "sufi", "melody", "chola"],
    moodTags: ["Relaxed", "Romantic", "Emotional"]
  },
  {
    title: "Anirudh: The Rock-Star Symphony",
    description: "The energetic high-voltage musical landscape behind contemporary South Indian mega-hits including Leo, Vikram, Jailer, and Master.",
    type: "Music",
    genres: ["Musical", "Action"],
    language: "Tamil",
    releaseYear: 2023,
    runtime: "80 min",
    rating: 9.2,
    ratingCount: 2900,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music112/v4/5a/8f/fc/5a8ffc04-f5aa-873a-4467-31350a498522/196589139360.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/1v_4G0Y1c0c",
    cast: ["Anirudh Ravichander", "Arivu", "Anthony Daasan"],
    director: "Anirudh Ravichander",
    popularity: 98,
    tags: ["badass", "hukum", "naa ready", "bass boosted"],
    moodTags: ["Energetic", "Excited"]
  },
  {
    title: "After Hours",
    description: "The fourth studio album by Canadian singer the Weeknd, exploring new wave, synth-pop and dream pop themes of heartbreak and redemption under city lights.",
    type: "Music",
    genres: ["Musical", "Romance"],
    language: "English",
    releaseYear: 2020,
    runtime: "56 min",
    rating: 8.9,
    ratingCount: 2600,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/bb/1b/2d/bb1b2d56-78e7-e17f-7140-5b5cb32585f9/20UMGIM09689.rgb.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/4NRXx6U8ABQ",
    cast: ["The Weeknd", "Metro Boomin", "Max Martin"],
    director: "The Weeknd",
    popularity: 96,
    tags: ["blinding lights", "save your tears", "synth-pop", "neon noir"],
    moodTags: ["Lonely", "Energetic", "Romantic"]
  },
  {
    title: "Folklore",
    description: "Taylor Swift's intimate eighth studio album recorded during isolation, showcasing melancholic indie-folk storytelling and acoustic tranquility.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2020,
    runtime: "63 min",
    rating: 8.8,
    ratingCount: 3100,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/8b/09/b3/8b09b307-5509-f1fb-6901-b8efd8eb8307/20UMGIM67657.rgb.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/osdoLjUNFnA",
    cast: ["Taylor Swift", "Aaron Dessner", "Jack Antonoff", "Bon Iver"],
    director: "Taylor Swift",
    popularity: 94,
    tags: ["cardigan", "exile", "cottagecore", "acoustic"],
    moodTags: ["Relaxed", "Lonely", "Emotional"]
  },
  {
    title: "To Pimp a Butterfly",
    description: "Kendrick Lamar's masterpiece exploring African-American culture, racial inequality, institutional depression, and musical heritage through jazz, funk, and spoken word.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2015,
    runtime: "79 min",
    rating: 9.5,
    ratingCount: 3400,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/ec/3b/b7/ec3bb748-0242-a8c6-3023-74ec9c916297/15UMGIM13410.rgb.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/s0QtdISwioc",
    cast: ["Kendrick Lamar", "George Clinton", "Thundercat", "Snoop Dogg"],
    director: "Kendrick Lamar",
    popularity: 95,
    tags: ["alright", "king kunta", "hip-hop", "pulitzer artist"],
    moodTags: ["Curious", "Energetic"]
  },
  {
    title: "The Dark Side of the Moon",
    description: "Pink Floyd's landmark progressive rock concept album exploring conflict, greed, time, death, and mental illness.",
    type: "Music",
    genres: ["Musical", "Sci-Fi"],
    language: "English",
    releaseYear: 1973,
    runtime: "43 min",
    rating: 9.6,
    ratingCount: 4200,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/f4/04/b8/f404b8ce-3909-00e9-b541-e9ee2999e0df/5099902895558.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/DLOth-BuCNY",
    cast: ["David Gilmour", "Roger Waters", "Richard Wright", "Nick Mason"],
    director: "Pink Floyd",
    popularity: 93,
    tags: ["prism", "time", "money", "psychedelic rock"],
    moodTags: ["Curious", "Relaxed"]
  },
  {
    title: "Pritam & Arijit Singh - Soulful Serenades",
    description: "The heartwarming collaborations between music director Pritam and romantic voice Arijit Singh across iconic Bollywood soundtracks.",
    type: "Music",
    genres: ["Musical", "Romance"],
    language: "Hindi",
    releaseYear: 2022,
    runtime: "65 min",
    rating: 9.0,
    ratingCount: 2700,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/05/85/ca/0585ca42-e1d2-0690-3486-2a62319ef472/8902894356498_cover.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/BddP6PYo2gs",
    cast: ["Arijit Singh", "Pritam Chakraborty", "Amitabh Bhattacharya"],
    director: "Pritam",
    popularity: 95,
    tags: ["channa mereya", "kesariya", "bollywood romance", "melodious"],
    moodTags: ["Romantic", "Emotional", "Happy"]
  },
  {
    title: "Map of the Soul: 7",
    description: "BTS's introspective studio album reflecting on their seven years together as a group and embracing both their public personas and private shadows.",
    type: "Music",
    genres: ["Musical", "Comedy"],
    language: "Korean",
    releaseYear: 2020,
    runtime: "74 min",
    rating: 8.8,
    ratingCount: 3800,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music124/v4/ec/d7/89/ecd78964-b816-7241-1559-00366ebf7b11/cover-Bighit_BTS_MOTS7.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/mPVDGOVjRQ0",
    cast: ["RM", "Jin", "Suga", "J-Hope", "Jimin", "V", "Jungkook"],
    director: "Big Hit Music",
    popularity: 96,
    tags: ["on", "black swan", "k-pop", "global phenomenon"],
    moodTags: ["Energetic", "Happy"]
  },
  {
    title: "Ludwig Göransson: Oppenheimer Score",
    description: "The Academy Award-winning soundtrack crafted purely using violin oscillations and intense polyrhythmic pulses to depict the fiery birth of the atomic age.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2023,
    runtime: "94 min",
    rating: 9.2,
    ratingCount: 1900,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music126/v4/31/6f/a7/316fa7a4-3701-a083-d5d3-82ef2f8a8bbd/23UMGIM78077.rgb.jpg/600x600bb.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/rLb2cwF3Pazuxaj0sRXQ037tGI1.jpg",
    trailer: "https://www.youtube.com/embed/t9tQ7e8dK4w",
    cast: ["Ludwig Göransson"],
    director: "Ludwig Göransson",
    popularity: 93,
    tags: ["can you hear the music", "trinity", "violin", "cinematic"],
    moodTags: ["Curious", "Excited"]
  },
  {
    title: "Happier Than Ever",
    description: "Billie Eilish's sophomore album exploring fame, abuse, privacy and emotional growth, transitioning from delicate bossa nova to roaring rock crescendos.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2021,
    runtime: "56 min",
    rating: 8.6,
    ratingCount: 2100,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/d5/9c/6a/d59c6ab6-ec0d-c052-bb53-61f251c6b541/21UMGIM39257.rgb.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/5GJWxDKyk3A",
    cast: ["Billie Eilish", "FINNEAS"],
    director: "Billie Eilish",
    popularity: 91,
    tags: ["title track", "introspective", "alternative pop", "finneas"],
    moodTags: ["Emotional", "Lonely"]
  },
  {
    title: "Sid Sriram: Soul & Classical Vibrations",
    description: "A signature blend of Carnatic classical precision and modern contemporary soul vocals in celebrated South Indian tracks.",
    type: "Music",
    genres: ["Musical", "Romance"],
    language: "Tamil",
    releaseYear: 2023,
    runtime: "65 min",
    rating: 8.9,
    ratingCount: 1800,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music115/v4/80/4f/2e/804f2e62-c174-8b6a-2082-f6e3cbf903d6/8903431787121.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/0Q2fW6qL0x8",
    cast: ["Sid Sriram"],
    director: "Sid Sriram",
    popularity: 92,
    tags: ["ennodu nee irundhaal", "kannaana kanne", "soulful", "carnatic"],
    moodTags: ["Romantic", "Relaxed"]
  },
  {
    title: "21",
    description: "Adele's iconic second studio album detailing heart-wrenching separation and personal discovery with powerful soulful blues anthems.",
    type: "Music",
    genres: ["Musical", "Drama"],
    language: "English",
    releaseYear: 2011,
    runtime: "48 min",
    rating: 9.1,
    ratingCount: 3300,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music114/v4/91/9f/f0/919ff089-7cfc-60fa-238a-f58c42a2d480/886443317769.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/rYEDA3JcQqw",
    cast: ["Adele", "Paul Epworth", "Rick Rubin"],
    director: "Adele",
    popularity: 93,
    tags: ["rolling in the deep", "someone like you", "grammy winner"],
    moodTags: ["Emotional", "Lonely"]
  },
  {
    title: "Kind of Blue",
    description: "The definitive jazz record in history, Miles Davis' modal jazz masterpiece features John Coltrane and Bill Evans in timeless improvisational splendor.",
    type: "Music",
    genres: ["Musical"],
    language: "English",
    releaseYear: 1959,
    runtime: "45 min",
    rating: 9.6,
    ratingCount: 2900,
    poster: "https://is1-ssl.mzstatic.com/image/thumb/Music125/v4/ca/87/0d/ca870d89-4fa2-fa01-6c2e-4363294c77c6/886444078508.jpg/600x600bb.jpg",
    backdrop: "https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=1200&auto=format&fit=crop&q=80",
    trailer: "https://www.youtube.com/embed/kbxtYqA6ypM",
    cast: ["Miles Davis", "John Coltrane", "Bill Evans", "Cannonball Adderley"],
    director: "Miles Davis",
    popularity: 91,
    tags: ["so what", "modal jazz", "legendary trumpet", "relaxing"],
    moodTags: ["Relaxed", "Lonely"]
  }
];

async function seedDataIfEmpty() {
  const existingCount = await Content.countDocuments({});
  if (existingCount > 0) {
    console.log(`[Seeder] Database already populated with ${existingCount} items.`);
    return;
  }
  await runSeeder();
}

async function runSeeder() {
  console.log('[Seeder] Starting CineMind AI database population...');

  // 1. Wipe existing content and users for clean state
  await Content.deleteMany({});
  await User.deleteMany({});
  await Rating.deleteMany({});
  await WatchHistory.deleteMany({});
  await SearchHistory.deleteMany({});

  const contentDataPath = path.join(__dirname, '..', 'data', 'content.json');
  let contentToInsert = seedContent;
  if (fs.existsSync(contentDataPath)) {
    try {
      const parsed = JSON.parse(fs.readFileSync(contentDataPath, 'utf8'));
      if (Array.isArray(parsed) && parsed.length > 0) contentToInsert = parsed;
    } catch(e) {}
  }

  console.log(`[Seeder] Inserting ${contentToInsert.length} entertainment titles...`);
  const insertedContent = await Content.insertMany(contentToInsert);
  console.log(`[Seeder] Successfully seeded ${insertedContent.length} titles.`);

  // 2. Create Demo User
  console.log('[Seeder] Creating demo user account...');
  const demoUser = await User.create({
    name: 'Alex Mercer',
    username: 'demouser',
    email: 'demo@cinemind.ai',
    password: 'Demo@123',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=200',
    dob: '1998-05-14',
    favoriteGenres: ['Sci-Fi', 'Thriller', 'Action', 'Animation'],
    preferredLanguages: ['English', 'Tamil', 'Korean', 'Japanese'],
    preferredContentTypes: ['Movie', 'TV Show', 'Anime', 'Music'],
    role: 'user',
    status: 'active'
  });

  // 3. Create Admin Account
  console.log('[Seeder] Creating admin account...');
  const adminUser = await User.create({
    name: 'CineMind Administrator',
    username: 'admin',
    email: 'admin@cinemind.ai',
    password: 'Admin@123',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=200',
    dob: '1990-01-01',
    favoriteGenres: ['Sci-Fi', 'Crime', 'Documentary'],
    preferredLanguages: ['English', 'Tamil', 'Hindi'],
    preferredContentTypes: ['Movie', 'TV Show', 'Web Series', 'Anime', 'Music'],
    role: 'admin',
    status: 'active'
  });

  // 4. Attach initial Watchlist, Liked Content, and Watch History to Demo User
  const interstellar = insertedContent.find(c => c.title === 'Interstellar') || insertedContent[0];
  const vikram = insertedContent.find(c => c.title === 'Vikram') || insertedContent[1];
  const strangerThings = insertedContent.find(c => c.title === 'Stranger Things') || insertedContent[2];
  const aot = insertedContent.find(c => c.title === 'Attack on Titan') || insertedContent[3];
  const daftPunk = insertedContent.find(c => c.title === 'Discovery') || insertedContent[4];
  const huberman = insertedContent.find(c => c.title === 'Huberman Lab') || insertedContent[5];

  const initialWatchlist = [String(vikram._id), String(strangerThings._id), String(aot._id)];
  const initialLiked = [String(interstellar._id), String(daftPunk._id)];

  await User.findByIdAndUpdate(demoUser._id, {
    watchlist: initialWatchlist,
    likedContent: initialLiked
  });

  // 5. Seed Watch History for Demo User
  await WatchHistory.create([
    {
      userId: String(demoUser._id),
      contentId: String(interstellar._id),
      contentTitle: interstellar.title,
      contentPoster: interstellar.poster,
      contentType: interstellar.type,
      progress: 100,
      completed: true,
      watchedDurationMinutes: 169,
      watchedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString()
    },
    {
      userId: String(demoUser._id),
      contentId: String(vikram._id),
      contentTitle: vikram.title,
      contentPoster: vikram.poster,
      contentType: vikram.type,
      progress: 65,
      completed: false,
      watchedDurationMinutes: 110,
      watchedAt: new Date(Date.now() - 48 * 3600 * 1000).toISOString()
    },
    {
      userId: String(demoUser._id),
      contentId: String(huberman._id),
      contentTitle: huberman.title,
      contentPoster: huberman.poster,
      contentType: huberman.type,
      progress: 40,
      completed: false,
      watchedDurationMinutes: 50,
      watchedAt: new Date(Date.now() - 72 * 3600 * 1000).toISOString()
    }
  ]);

  // 6. Seed Sample Community Ratings & Reviews
  await Rating.create([
    {
      userId: String(demoUser._id),
      userName: demoUser.name,
      userAvatar: demoUser.avatar,
      contentId: String(interstellar._id),
      contentTitle: interstellar.title,
      rating: 5,
      review: "A monumental cinematic triumph. Nolan and Zimmer delivered an emotional, intellectually profound space odyssey.",
      createdAt: new Date().toISOString()
    },
    {
      userId: String(adminUser._id),
      userName: adminUser.name,
      userAvatar: adminUser.avatar,
      contentId: String(interstellar._id),
      contentTitle: interstellar.title,
      rating: 5,
      review: "Peak sci-fi cinema with breathtaking physics grounding and emotional payoff.",
      createdAt: new Date().toISOString()
    },
    {
      userId: String(demoUser._id),
      userName: demoUser.name,
      userAvatar: demoUser.avatar,
      contentId: String(vikram._id),
      contentTitle: vikram.title,
      rating: 5,
      review: "Sensational theatrical experience! Kamal Haasan and Anirudh's score elevate this to another dimension.",
      createdAt: new Date().toISOString()
    }
  ]);

  console.log('\n================================================================');
  console.log('✅ CineMind AI database successfully seeded!');
  console.log('👤 Demo User:  demo@cinemind.ai   | Password: Demo@123');
  console.log('👑 Admin User:  admin@cinemind.ai  | Password: Admin@123');
  console.log(`🎬 Total titles: ${insertedContent.length}`);
  console.log('================================================================\n');
}

if (require.main === module) {
  (async () => {
    await connectDB();
    await runSeeder();
    process.exit(0);
  })();
}

module.exports = {
  seedContent,
  runSeeder,
  seedDataIfEmpty
};
